// Extracts the proposal paragraphs, the 61 sentences and the original glossary
// from the user's original guide so the rebuilt guide quotes them verbatim.
// Usage: node grfp/tools/extract-source.mjs
import fs from 'node:fs';
import path from 'node:path';
const here = path.dirname(new URL(import.meta.url).pathname);
const root = path.resolve(here, '..');
const html = fs.readFileSync(path.join(root, 'reference/original-guide.html'), 'utf8');
const m = html.match(/<script type="application\/json" id="guide-data">([\s\S]*?)<\/script>/);
if (!m) throw new Error('guide-data block not found');
const d = JSON.parse(m[1]);
const paragraphs = d.paragraphs.map(({ id, page, title, text }) => ({ id, page, title, text }));
const sentences = d.sentences.map(({ id, pid, page, section, text, plain, why, watch }) => ({ id, pid, page, section, text, plain, why, watch }));
// Every sentence must appear verbatim inside its paragraph.
for (const s of sentences) {
  const p = paragraphs.find((x) => x.id === s.pid);
  if (!p || !p.text.includes(s.text)) throw new Error(`Sentence ${s.id} not found verbatim in ${s.pid}`);
}
const out = `/* Generated by tools/extract-source.mjs from reference/original-guide.html — do not edit by hand.
   Proposal text is reproduced verbatim (line-wrap normalization only). */
window.WC = window.WC || {};
WC.source = ${JSON.stringify(d.source)};
WC.paragraphs = ${JSON.stringify(paragraphs, null, 0)};
WC.sentences = ${JSON.stringify(sentences, null, 0)};
WC.refNotes = ${JSON.stringify(d.notes.map((n) => ({ id: n.id, html: n.html })), null, 0)};
WC.glossaryBase = ${JSON.stringify(d.glossary.map((g) => ({ term: g.term, def: g.definition, src: g.source })), null, 0)};
`;
fs.writeFileSync(path.join(root, 'src/data/proposal-base.js'), out);
console.log(`paragraphs ${paragraphs.length}, sentences ${sentences.length}, glossary ${d.glossary.length}`);
